### ISSUE TITLE
Misformatting comment before item in list

### ISSUE THREAD

**Issue by programmerjake** [tamasfe/taplo#109]
I'm using v0.12.1

When trying to format my `Cargo.toml` file, it incorrectly moves a comment:
```toml
[features]
myfeature = [
    "feature1",
    # needed because blah blah blah reason that only makes sense when attached to feature2
    "feature2",
]
# comment2
nextfeature = []
```
Formats to:
```toml
[features]
myfeature = [
    "feature1",
    
    "feature2",
] # needed because blah blah blah reason that only makes sense when attached to feature2
# comment2
nextfeature = []
```

This makes it difficult to understand the comment since it breaks the attachment to `feature2`

**Comment by Profpatsch** [comment]
I stumbled into the same problem.

**Comment by ShadowLNC** [comment]
I'm finding it actually **deletes** all comments except the last one inside an array (v0.12.2):

```toml
[main]
my_array = [
    #Items
    "a",
    "b", # Some comment
    "c", # This is special

    # Other items
    "d",
    "e",
    "f",

    # Some other items we decided not to include
    # "g",
    # "h",
    # "i",
    
    "item",
]
```

Becomes:

```toml
[main]
my_array = [
    
    "a",
    "b", 
    "c", 
    
    "d",
    "e",
    "f",
    
    
    
    
    "item",
] # "i",
```
