### ISSUE TITLE
Add an option to control array space

### ISSUE THREAD

**Issue by GalAster** [tamasfe/taplo#12]
Add an option to control the space between `[ ]` and data.

```toml
# array_filling_space = 0
array_compact = [0, [1], [[2]]]
# array_filling_space = 1
array_free        = [ 0, [ 1 ], [ [ 2 ] ] ]
```
