### ISSUE TITLE
False positive "duplicate key" with dotted keys + non-dotted key

### ISSUE THREAD

**Issue by caass** [tamasfe/taplo#125]
Hello! I'm getting some false positives when looking at a toml that contains two dotted keys, followed by a non-dotted key of the same name:

```toml
[hello.world]
swag = true

[hello.friends]
asdf = "jkl;"

[hello]
marked_as_duplicate = true
```

this seems fine:

```toml
[hello.world]
swag = true

[hello]
marked_as_duplicate = false
```

and this also works:

```toml
[hello.world]
swag = true

[hello.friends]
asdf = "jkl;"

[hello.my-ragtime-gal]
marked_as_duplicate = false
```

A real-world example of this can be found [here](https://github.com/alacritty/alacritty/blob/master/alacritty/Cargo.toml).
