### ISSUE TITLE
Wrong inline table format

### ISSUE THREAD

**Issue by zmtq05** [tamasfe/taplo#132]
Formatting `Cargo.toml` in vscode.

version `0.12.2`:
```toml
[dependencies]
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
```

version `0.12.3`:
```toml
[dependencies]
reqwest = { version="0.11.4", features=["json"] }
serde = { version="1.0.126", features=["derive"] }
serde_json = "1.0.64"
```

There is no space both before and after the `=` between a key and value.
