### ISSUE TITLE
Wrong formatting on table headers

### ISSUE THREAD

**Issue by Emilgardis** [tamasfe/taplo#138]
Extension Version: 0.14.0
Version: 1.59.0-insider (user setup)
Commit: 87d692b7bf1eb5a663b3e62620a6e7e436e1838c
Date: 2021-07-09T05:13:26.890Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

```toml
[a]
hello = "world"
[b]
foo=["bar"]
```

formats wrongly to

```toml
[a]
[b]hello = "world"
foo = ["bar"]
```

adding an empty line before `[b]` fixes the issue.
