### ISSUE TITLE
(VS) Excluded files not excluded from linting

### ISSUE THREAD

**Issue by jwalton512** [tamasfe/taplo#140]
Given the following configuration:
```toml
# .taplo.toml
exclude = ["{{cookiecutter.project_slug}}/pyproject.toml"]

[formatting]
reorder_keys = true
```

and a template for pyproject.toml
```toml
# ./{{cookiecutter.project_slug}}/pyproject.toml
[tool.poetry]
name = "{{ cookiecutter.project_name }}"
description = "{{ cookiecutter.project_description }}"
version = "{{ cookiecutter.project_version }}"
authors = ["{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>"]
license = "{{ cookiecutter.license }}"
```

the excluded file does not get reformatted which **is** expected/desired, however, linting/warnings do occur for incorrect content (specifically for `authors` in the above example.  As this is part of a project skeleton ([cookiecutter](https://cookiecutter.readthedocs.io/en/1.7.3/README.html) which uses [Jinja2](https://jinja2docs.readthedocs.io/en/stable/) templates (for naming files, variables, etc) it is expected that the files won't meet the expected schema.

I was able to hack a solution which was to associate the file with an empty schema:
```json
{
    "evenBetterToml.schema.associations": {
        ".*cookie.*toml": ""
    }
}
```
but this doesn't seem optimal as it generates background warnings in vscode.

Is it possible to exclude a file from linting altogether, while keeping the extension active for other toml files within the project?
