### ISSUE TITLE
Deleting right array bracket ] makes contents disappear on save

### ISSUE THREAD

**Issue by Fogapod** [tamasfe/taplo#145]
before save
```toml
[dependencies]
futures = { version = "0.3.15", features = ["executor", 123 }
```
after save
```toml
[dependencies]
futures = { version = "0.3.15", features = [ }
```

**Comment by Fogapod** [comment]
Similar bug, not sure if related:
before:
```toml
[dependencies]
futures = version = "0.3.15" 
```
after:
```toml
[dependencies]
futures = version
```
