### ISSUE TITLE
[VSCODE] Indentation issue with Indent Entries & Indent Tables settings enabled

### ISSUE THREAD

**Issue by Tom-Ski** [tamasfe/taplo#146]
When combining a nested table which has an array of tables, another root table outside of the nested table does not get indented correctly.

The second `table` named `Root Table 2` does not get indenting which should be aligned with the first table in the array `Root Table 1`
Version: v0.14.2

How Toml is formatted by the plugin
```toml
[[table]]
    name = "Root Table 1"
    [table.nestedtable]
        name = "Nested parent"
        [[table.nestedtable.subtable]]
            name = "Subtable 1"
        [[table.nestedtable.subtable]]
            name = "Subtable 2"

    [[table]]
    name = "Root Table 2"

```

Json representation
```js
{
  "table": [
    {
      "name": "Root Table 1",
      "nestedtable": {
        "name": "Nested parent",
        "subtable": [
          {
            "name": "Subtable 1"
          },
          {
            "name": "Subtable 2"
          }
        ]
      }
    },
    {
      "name": "Root Table 2"
    }
  ]
}
```
