### ISSUE TITLE
Rule does not work

### ISSUE THREAD

**Issue by hituzi-no-sippo** [tamasfe/taplo#172]
Thank you for creating this wonderful tool.

[rule](https://taplo.tamasfe.dev/configuration/#rules) does not work in the following case.

Taplo version is `Taplo TOML Utility 0.4.1 (x86_64-unknown-linux-gnu)`.

### taplo.toml

```toml
[formatting]
reorder_keys = false

[[rule]]
include = ['rule_test.toml']
keys = ['reorder']

[rule.formatting]
reorder_keys = true
```

### rule_test.toml

Before run `taplo format rule_test.toml` command.

```toml
[reorder]
b = true
a = true
```

After run `taplo format rule_test.toml` command.

```toml
[reorder]
b = true
a = true
```

It is set to `reorder_keys = true`, but it is not reordered.

### Expected

Expect to reorder them as follows.

```toml
[reorder]
a = true
b = true
```

### taplo.toml

Same as the case where it does not work.

```toml
[formatting]
reorder_keys = false

[[rule]]
include = ['rule_test.toml']
keys = ['reorder']

[rule.formatting]
reorder_keys = true
```

#### Case 1

Before run `taplo format rule_test.toml` command.

```toml
[reorder]
b = true
a = true

c = true
```

After run `taplo format rule_test.toml` command.

```toml
[reorder]
a = true
b = true

c = true
```

#### Case 2

Before run `taplo format rule_test.toml` command.

```toml
[reorder]
b = true
a = true

[not_reorder]
c = true
```

After run `taplo format rule_test.toml` command.

```toml
[reorder]
a = true
b = true

[not_reorder]
c = true
```

## Case that keys is multiple elements

It doesn't work with `keys` is multiple element (e.g. `keys = ['apple', 'banana']`) as well.

### taplo.toml

```toml
[[rule]]
include = ['rule_test.toml']
keys = ['apple', 'banana']

[rule.formatting]
reorder_keys = true
```

### rule_test.toml

Before run `taplo format rule_test.toml` command.

```toml
[apple]
b = true
a = true

[banana]
b = true
a = true
```

After run `taplo format rule_test.toml` command.

```toml
[apple]
a = true
b = true

[banana]
b = true
a = true
```

### Expected

Expect to reorder them as follows.

```toml
[apple]
a = true
b = true

[banana]
a = true
b = true
```
