### ISSUE TITLE
VS Code extension not applying formatting defined in .taplo.toml automatically

### ISSUE THREAD

**Issue by skyzyx** [tamasfe/taplo#179]
I develop devtools for my company, and I'm looking into using EvenBetterTOML to help assist with formatting and JSONSchema-based autocompletion for the developers I support.

I read the docs, installed the EvenBetterTOML extension for VS Code, and created a new `.taplo.toml` file at the root of the repo with the following contents:

```toml
include = ["configuration.toml"]

[schema]
path = "/Users/rparman/.schemas/compiled-schema.json"
enabled = true

[formatting]
align_entries = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
column_width = 80
indent_tables = true
indent_string = "  "
trailing_newline = true
reorder_keys = false
allowed_blank_lines = 2
crlf = false
```

I performed zero other configuration, no changes to VS Code’s settings. After reloading VS Code, I made a change to `configuration.toml`, hit save, and expected that my TOML document would reformat before my eyes…

But it didn't. :(

It would be great to add this config file to the repository, tell people to install the VS Code extension, and the formatting in the config file is automatically applied to the `configuration.toml` file. Like how `.editorconfig` files work.

I started poking around in the settings, and ensured that `"evenBetterToml.taploConfig": ".taplo.toml",` was _explicitly_ written to VS Code’s settings.json file. Re-saved `configuration.toml`, and _now_ it applied.

So now, I also have to ship a `.vscode/settings.json` file in my repo. While this isn't necessarily _hard_, it's taken me a couple of hours to figure this out. :/

Is there a good way to have the VS Code extension _automatically_ read `.taplo.toml` by default, whether the key in the settings file exists or not?
