### ISSUE TITLE
Poetry schema changes for upcomming v1.2

### ISSUE THREAD

**Issue by Cielquan** [tamasfe/taplo#204]
Poetry v1.2 will introduce dependency groups which have there own entries in the pyproject.toml file. 

I currently use the v1.2 alpha version and Even Better Toml throws me the "unknown property" error for those new keys or rather the first occurrence.

>  To declare a new dependency group, use a tool.poetry.group.`<group>` section where `<group>` is the name of your dependency group (for instance, test):
> 
> ```toml
> [tool.poetry.group.test]  # This part can be left out
> 
> [tool.poetry.group.test.dependencies]
> pytest = "^6.0.0"
> pytest-mock = "*"
> ```

Source: https://python-poetry.org/docs/master/managing-dependencies/

**Comment by dcode** [comment]
Further, all development dependencies are moving to a group called `dev`. For instance: 

```toml
[tool.poetry.group.dev.dependencies]
mypy           = "^0.950"
pytest         = "^6.0"
pytest-isort   = "^3.0.0"
pytest-flake8  = "^1.0"
pytest-black   = "^0.3.12"
pytest-datadir = "^1.3.1"
```
