### ISSUE TITLE
Bug: Rule not applying to last table entry

### ISSUE THREAD

**Issue by Purpzie** [tamasfe/taplo#256]
`.taplo.toml`:
```toml
[formatting]
column_width = 100
indent_string = '	'
reorder_keys = true

# I don't want the package field or individual dependency tables to be reordered.
# The list of dependencies *should* be ordered, however.
[[rule]]
formatting = { reorder_keys = false }
include = ["**/Cargo.toml"]
keys = ["package", "dependencies.*"]
```

`Cargo.toml` after using taplo:
```toml
[package]
name = "twilight"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
paste = "1.0.7"

[dependencies.twilight-cache-inmemory]
version = "0.11.0"
features = ["permission-calculator"]
default-features = false

[dependencies.twilight-gateway]
version = "0.11.0"
features = ["native", "zlib-stock"]
default-features = false

[dependencies.twilight-http]
version = "0.11.0"
features = ["decompression"]
default-features = false

[dependencies.twilight-model]
version = "0.11.0"
features = []
default-features = false

[dependencies.twilight-standby]
version = "0.11.0"
features = []
default-features = false

# Notice how this one still gets reordered.
# You could switch any dependency to be here and it would get reordered too.
[dependencies.twilight-util]
default-features = false
features = ["builder", "link", "snowflake"]
version = "0.11.0"
```
