### ISSUE TITLE
Table with dotted keys produces wrong output

### ISSUE THREAD

**Issue by Yesterday17** [tamasfe/taplo#258]
Generated on https://taplo.tamasfe.dev/editor/

## TOML
```toml
[album]
album_id = "eeae9d38-275d-470f-a46c-7e97197a4aef"
title = "Rewrite Original SoundTrack"
artist = "Key Sounds Label"
date = 2011-10-28
type = "absolute"
catalog = "KSLA-0073~5"
tags = ["Rewrite"]

[[discs]]
catalog = "KSLA-0073"

[[discs.tracks]]
title = "Philosophyz"
artist = "水谷瑠奈"
type = "normal"
artists.vocal = "水谷瑠奈"
artists.composer = "折戸伸治"
artists.arranger = "a2c"
artists.lyricist = "都乃河勇人"
```

### Output
```json
{
  "album": {
    "album_id": "eeae9d38-275d-470f-a46c-7e97197a4aef",
    "title": "Rewrite Original SoundTrack",
    "artist": "Key Sounds Label",
    "date": "2011-10-28",
    "type": "absolute",
    "catalog": "KSLA-0073~5",
    "tags": [
      "Rewrite"
    ]
  },
  "discs": [
    {
      "catalog": "KSLA-0073",
      "tracks": [
        {
          "title": "Philosophyz",
          "artist": "水谷瑠奈",
          "type": "normal",
          "artists": {
            "artists": {
              "artists": {
                "vocal": "水谷瑠奈",
                "composer": "折戸伸治"
              },
              "arranger": "a2c"
            },
            "lyricist": "都乃河勇人"
          }
        }
      ]
    }
  ]
}
```

## Expected
```json
{
  "album": {
    "album_id": "eeae9d38-275d-470f-a46c-7e97197a4aef",
    "title": "Rewrite Original SoundTrack",
    "artist": "Key Sounds Label",
    "date": "2011-10-28",
    "type": "absolute",
    "catalog": "KSLA-0073~5",
    "tags": [
      "Rewrite"
    ]
  },
  "discs": [
    {
      "catalog": "KSLA-0073",
      "tracks": [
        {
          "title": "Philosophyz",
          "artist": "水谷瑠奈",
          "type": "normal",
          "artists": {
            "vocal": "水谷瑠奈",
            "composer": "折戸伸治",
            "arranger": "a2c",
            "lyricist": "都乃河勇人"
          }
        }
      ]
    }
  ]
}
```

The expected json is generated from the following `toml`:
```toml
[album]
album_id = "eeae9d38-275d-470f-a46c-7e97197a4aef"
title = "Rewrite Original SoundTrack"
artist = "Key Sounds Label"
date = 2011-10-28
type = "absolute"
catalog = "KSLA-0073~5"
tags = ["Rewrite"]

[[discs]]
catalog = "KSLA-0073"

[[discs.tracks]]
title = "Philosophyz"
artist = "水谷瑠奈"
type = "normal"
artists = { vocal = "水谷瑠奈", composer = "折戸伸治", arranger = "a2c", lyricist = "都乃河勇人" }
```
