### ISSUE TITLE
format ignores options when no `taplo.toml` file exists

### ISSUE THREAD

**Issue by olix0r** [tamasfe/taplo#274]
New versions of taplo / Even Better TOML do not properly format arrays, which causes lots of unnecessary changes when working in a project that already used Even Better TOML. 

I'm seeing this via VS Code but I can replicate the behavior via the CLI.

1. I create a TOML file with an array:

```toml
[section]
array = ["one", "two", "three", "four five six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen"]
```

2. I run the formatter with `-o indent_string=".   "` (that is, with a 4-space indent):

```
:; ./taplo format -o indent_string="    " foo.toml
 INFO taplo:format_files:collect_files: found files total=1 excluded=0 cwd="/tmp"
```

3. The file is formatted with a 2-space indent (which I believe is the default):

```toml
[section]
array = [
  "one",
  "two",
  "three",
  "four five six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
]
```

```
:; ./taplo --version
taplo 0.6.8
```

---

Furthermore, in VS Code, I'd prefer to not have to configure `indent_string` at all, since the editor already maintains settings for indent preferences:

* `editor.insertSpaces`
* `editor.tabSize`

I can open a separate issue for deriving the configuration, though.
