### ISSUE TITLE
No description for array of tables and its properties

### ISSUE THREAD

**Issue by danez** [tamasfe/taplo#278]
I have the following schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "plugins": {
      "type": "array",
      "default": [{ "package": "" }],
      "items": {
        "type": "object",
        "title": "Build Plugins",
        "description": "Build Plugins extend the functionality of the build process",
        "properties": {
          "package": {
            "type": "string",
            "description": "Package name of the build plugin"
          }
        }
      }
    }
  }
}
```

and the following toml file:

```toml
[[plugins]]

package = "asd"
```

In this case there is not description when I hover `package` in vscode. the description only shows up when hovering the value `"asd"`

**Comment by ed-curran** [comment]
I think this my be related to this: https://github.com/tamasfe/taplo/issues/355

**Comment by lucasfernog-crabnebula** [comment]
I'm also facing this issue.

**Comment by umnovI** [comment]
I am facing the same issue with this schema https://github.com/umnovI/dioxus-config-schema/blob/main/dioxus.schema.json
And this .toml file:
```toml
#:schema https://raw.githubusercontent.com/umnovI/dioxus-config-schema/main/dioxus.schema.json
# Docs: https://dioxuslabs.com/learn/0.5/CLI/configure

[application]

# App (Project) Name
name = "web-test"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "web-test"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["test"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[[web.proxy]]

backend = "http://localhost:8000/api/"

```
Even tho I get autocomplete:
![image](https://github.com/tamasfe/taplo/assets/30232564/372400a2-adf8-4dbc-9c29-5396da3d79ef)

And I can see description on the value itself:
![image](https://github.com/tamasfe/taplo/assets/30232564/18d129c2-24b7-40ff-aef7-b9f49ed35fa3)

But hovering over `backend` or `[[web.proxy]]` shows nothing.
