### ISSUE TITLE
Why this error?

### ISSUE THREAD

**Issue by frederikhors** [tamasfe/taplo#294]
I'm using it with this Makefile.toml [for cargo-make](https://github.com/sagiegurari/cargo-make#performance-tuning) but I'm getting this strange error, why?

```toml
[config] # here the error
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
default_to_workspace = false
```

```
Additional properties are not allowed ('skip_git_env_info', 'skip_rust_env_info', 'skip_crate_env_info' were unexpected) Even Better TOML
```
