### ISSUE TITLE
extension warns on [project.optional-dependencies] in pyproject.toml

### ISSUE THREAD

**Issue by Barry1** [tamasfe/taplo#295]
By [PEP 0621](https://peps.python.org/pep-0621/) it is allowed to have a section `[project.optional-dependencies]` in your `pyproject.toml` to specify things sometimes knows as extras.
Your extension complains on this code 
```toml
[project]
name = "mwe"
version = "0.1.2.3"
description = "Testing"
authors = [{ name = "me", email = "me@you.org" }]
requires-python = ">=3.10"

[project.optional-dependencies]
ALLFEATURES = ["psutil", "hashlib", "icecream", "cpu_load_generator"]

```
with `Additional properties are not allowed ('ALLFEATURES' was unexpected)`

I think the warning is wrong.

**Comment by tamasfe** [comment]
This has to be updated in the JSON schema, it's found at schemastore here: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/pyproject.json

**Comment by Barry1** [comment]
> This has to be updated in the JSON schema, it's found at schemastore here: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/pyproject.json

Thanks for that quick reply. As I'm not that fluent in json schema descriptions - isn't that already implemented in [line 856 and following](https://github.com/SchemaStore/schemastore/blob/06882015c718cd7616d096cac40d93f1a8a072ca/src/schemas/json/pyproject.json#L856)?

**Comment by tamasfe** [comment]
Sorry, I missed this one.

> isn't that already implemented in [line 856 and following](https://github.com/SchemaStore/schemastore/blob/06882015c718cd7616d096cac40d93f1a8a072ca/src/schemas/json/pyproject.json#L856)?

There seems to be a `patternProperties` definition, but it allows only lowercase.

**Comment by frederikhors** [comment]
I'm having this issue in a simple `Cargo.toml` file like this:

```toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
common = { path = "../some" }
```

How can I help you fix this?
