### ISSUE TITLE
.taplo.toml schema path unable to use remote schema

### ISSUE THREAD

**Issue by AiroPi** [tamasfe/taplo#296]
I have a `.taplo.toml` file with this configuration : 
```toml
[schema]
path = 'https://raw.githubusercontent.com/discord-bugcenter/tags/toml-refactor/schema.json'
```
But I get this message (in "Event Better TOML LSP" output) : 
`WARN initialize:initialize: failed to load workspace configuration error=invalid schema path self.root=file:///Users/username/Documents/projects/tags`

I also tried with a relative path like : 
```toml
path = "./schema.json"
```

But got the same error message...
