### ISSUE TITLE
Crash on completion

### ISSUE THREAD

**Issue by segevfiner** [tamasfe/taplo#298]
I'm trying to complete in a `starship.toml` file, and the LSP crashes with:
```
panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a TOML value", line: 0, column: 0)', /home/runner/work/taplo/taplo/crates/taplo-lsp/src/handlers/completion.rs:687:72

Stack:

Error
    at AA.i.wbg.__wbg_new_693216e109162396 (/Users/segevfiner/.vscode/extensions/tamasfe.even-better-toml-0.16.5/dist/server.js:2:5793)
    at wasm://wasm/00f193b6:wasm-function[5220]:0x30e120
    at wasm://wasm/00f193b6:wasm-function[2302]:0x2bf012
    at wasm://wasm/00f193b6:wasm-function[4284]:0x30403a
    at wasm://wasm/00f193b6:wasm-function[3258]:0x2ebabe
    at wasm://wasm/00f193b6:wasm-function[237]:0x12f7af
    at wasm://wasm/00f193b6:wasm-function[2934]:0x2e0764
    at wasm://wasm/00f193b6:wasm-function[1316]:0x268710
    at wasm://wasm/00f193b6:wasm-function[61]:0x1451c
    at wasm://wasm/00f193b6:wasm-function[102]:0x95ef4
```

`starship.toml`:
```toml
[directory]
truncation_symbol = "…/"

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "erl "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "pulumi "
```

When pressing cmd+space when trying to complete in the `[directory]` section for example.

VS Code v1.70.0
Extension v0.16.5
