### ISSUE TITLE
Bug: formatting inserts `\t` as a literal two characters before my table entries

### ISSUE THREAD

**Issue by jasikpark** [tamasfe/taplo#303]
```toml
[[plugins]]
\tpackage = "/plugins/netlify-npm-install"
```

is what I get as a result of trying to save

```toml
[[plugins]]
  package = "/plugins/netlify-npm-install"
```

it inserts the literal characters `\` and `t` rather than a tab character, which makes my document invalid
