### ISSUE TITLE
Arrays in inline tables break strangely

### ISSUE THREAD

**Issue by maltekliemann** [tamasfe/taplo#304]
The following inline table...

```toml
parity-scale-codec = { default-features = false, features = ["derive", "max-encoded-len"], version = "3.0.0" }
```

...breaks into:

```toml
parity-scale-codec = { default-features = false, features = [
  "derive",
  "max-encoded-len",
], version = "3.0.0" }
```

I'm not sure if this is expected behavior. I find this to be very difficult and confusing to read. Other auto-formatters (from other languages) that I'm familiar tend to do something like the following:

```toml
parity-scale-codec = {
    default-features = false,
    features = ["device", "max-encoded-len"],
    version = "3.0.0",
}
```

But I would be ok with just not breaking the array and keeping the line longer that it is normally allowed to be. So, depending on whether the current behavior is correct, I would very much appreciate either a fix or an option for preventing arrays in inline tables from being expanded.
