### ISSUE TITLE
Comments after table titles receive warnings

### ISSUE THREAD

**Issue by QuarticCat** [tamasfe/taplo#315]
Here is an official example:

```toml
[[products]]
name = "Hammer"
sku = 738594937

[[products]]  # empty table within the array

[[products]]
name = "Nail"
sku = 284758393

color = "gray"
```

https://toml.io/en/v1.0.0#array-of-tables

And the extension will complain that:

![image](https://user-images.githubusercontent.com/70888415/188329690-34b475dc-aa57-4427-bc6e-8920637e99a4.png)
