### ISSUE TITLE
Version Key Is Required in `pyproject.toml`

### ISSUE THREAD

**Issue by BrutalSimplicity** [tamasfe/taplo#316]
It seems that the `taplo` cli will fail to validate schemas for `pyproject.toml` when the version is not specified despite the version not being required by the jsonschema specification.

You can reproduce with a `pyproject.toml` file like below:

```toml
[project]
name = "deployment_handler"
requires-python = ">=3.9"
```

This works.

```toml
[project]
name = "deployment_handler"
version = "1.0.0"
requires-python = ">=3.9"
```

It seems that taplo may be associating the `pyproject` file to another schema when `version` is not specified.
