### ISSUE TITLE
Comments get "aligned" too much

### ISSUE THREAD

**Issue by Rudxain** [tamasfe/taplo#323]
I have this `rustfmt`:
```toml
hard_tabs = true
max_width = 96 #mean 0x40 0x80
short_array_element_width_threshold = 8
```

And it gets formatted like this:
```toml
hard_tabs = true
max_width = 96                          #mean 0x40 0x80
short_array_element_width_threshold = 8
```

I don't like that. Is there some config param to keep comments where they are?
