### ISSUE TITLE
Reorder elements inside arrays

### ISSUE THREAD

**Issue by xamgore** [tamasfe/taplo#338]
Hi! I would like to implement a PR that would allow sorting arrays. How I expect it to work:

```toml
# before
teloxide = { version = "0.11", features = ["macros", "auto-send", "rocksdb-storage"] }

# after
teloxide = { version = "0.11", features = ["auto-send", "macros", "rocksdb-storage"] }
```

What do you think about the idea? Are you ready to help me?
