### ISSUE TITLE
vscode sticky scroll produces wrong result for table

### ISSUE THREAD

**Issue by xxchan** [tamasfe/taplo#344]
example:
```toml
[a.a]
dummy = """















"""
[a.b]
dummy = """















"""
[a.c]
dummy = """















"""
```

<img width="315" alt="image" src="https://user-images.githubusercontent.com/37948597/199014427-4a2fb5af-04fe-4949-aa9d-bfc57a9fc671.png">
 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/37948597/199014611-c6f894a6-f9ef-4611-bb09-5fdb7b314cc1.png">
 
In this case, `[a.a]` should not be sticky because it's not the parent for `[a.b]` and `[a.c]`
