### ISSUE TITLE
[BUG] Wrong Poetry schema

### ISSUE THREAD

**Issue by jaklan** [tamasfe/taplo#35]
```toml
[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
isort = "*"
flake8 = "*"
```
generates such an error:
```toml
the required property "python" is missing Even Better TOML
```
which is not true - `python` property is only needed in `dependencies` section.
