### ISSUE TITLE
Unexpected error on publish in Cargo.toml

### ISSUE THREAD

**Issue by Weasy666** [tamasfe/taplo#37]
With the below content in a `Cargo.toml` file, i get an error displayed on the `true` value of `publish`.
The error message is, or the messages are:
```
the value must be valid for at least one of the 2 schemas - Even Better TOML (Publish)
-----
invalid type: expected array, not boolean - Even Better TOML
-----
invalid enum value, expected to be one of {false} - Even Better TOML (Disable)
```

I guess this has something to do with the `Cargo.toml` scheme?

You can reproduce this with the following content.
``` toml
[package]
name = "async-graphql-rocket"
version = "1.17.10"
authors = [""]
edition = "2018"
description = "async-graphql for Rocket.rs"
publish = true  # this is where the error occurs
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql", "rocket"]
categories = ["network-programming", "asynchronous"]
```
