### ISSUE TITLE
Full regex support missing (e.g. neg lookahead)

### ISSUE THREAD

**Issue by jkellerer** [tamasfe/taplo#376]
JSON schema defines the following regex syntax: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

This includes extended things like negative lookahead but support for it is missing in taplo. https://docs.rs/fancy-regex/latest/fancy_regex/ should offer a drop-in replacement to make this work.

E.g. negative lookahead is needed when considering a schema like this:
```yaml
{
  "properties": {
    "global": { global-object... },
    ...
  }
  "patternProperties": {
    "^(?!global|other-global).*$": { standard-named-object... }
  }
}
```

that validates a file like: 

```toml
[global]
some-global-object-setting="..."

[custom-named-section]
some-standard-named-object-setting="..."
```

"patternProperties" must exclude "global" to not apply the schema of "standard-named-object" to it.
