### ISSUE TITLE
`--stdin-filepath` should affect application of rules

### ISSUE THREAD

**Issue by dtolnay** [tamasfe/taplo#414]
Currently if I have a config file like:

```toml
# taplo.toml

include = [
    "path/to/thing.toml",
    # ...
]

[formatting]
reorder_keys = false

[[rule]]
include = ["path/to/thing.toml"]
keys = ["dependencies", "target.*.dependencies"]
[rule.formatting]
reorder_keys = true
```

```toml
# path/to/thing.toml

[dependencies]
y = 1
x = 1
```

then, running `taplo format --config ./taplo.toml path/to/thing.toml`, it correctly applies `reorder_keys` to reorder x before y.

But if I run `taplo format --config ./taplo.toml --stdin-filepath path/to/thing.toml - <path/to/thing.toml`, x and y are not reordered, despite the applicable rule.

I would have expected rules to apply based on stdin-filepath.

Mentioning @lffg since `--stdin-filepath` was introduced by you in #250.
