### ISSUE TITLE
Bare keys and quoted keys are not equivalent

### ISSUE THREAD

**Issue by kkiyama117** [tamasfe/taplo#42]
# About

[Bare keys and quoted keys are equivalent on toml v1.0.0-rc.2](https://toml.io/en/v1.0.0-rc.2#keys) but taplo doesn't raise error

## Reproduction

- create toml file and write
  ```toml
  # THIS WILL NOT WORK
  spelling = "favorite"
  "spelling" = "favourite"
  ```
- create `multiple-key-2.toml` in `test-data/invalid` and write

  ```toml
  # https://toml.io/en/v1.0.0-rc.2#keys
  # THIS WILL NOT WORK
  spelling = "favorite"
  "spelling" = "favourite"

  ```
  after that,run `cargo run  --bin test-gen --package test-gen -- -i ../../test-data -o ../../taplo/src/tests` and run test at project root

## Notes
I'm trying to make tests from [TOML 1.0.0-rc.2](https://toml.io/en/v1.0.0-rc.2) now. It may solve #3, but I don't know which ones in `test-data` folder are needed. (almost all are same as toml.io's, but I can't find some ones.) I create [prototype of test data](https://github.com/kkiyama117/taplo/tree/f837018b242a83a6c02da3c07b56325f362c693a/test-data/1.0.0-rc.2) so please check and tell me I should proceed as it is or not if you can. (It refers to only toml.io and I've finished up to end of the [`keys`](https://toml.io/en/v1.0.0-rc.2#keys) section.)
