### ISSUE TITLE
Channel "esp" is flagged as invalid.

### ISSUE THREAD

**Issue by hackguy25** [tamasfe/taplo#420]
I'm using the [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) VS Code extension, which, if I understand correctly, uses Taplo as its backend.
I'm writing Rust for ESP32 microcontrollers, which require a [specific fork of the Rust toolchain](https://github.com/esp-rs/rust) that adds Xtensa support.
This toolchain does not provide the standard `stable`/`nightly`/`beta` channels, but instead exposes just one channel: `esp`.
As a result, the extension flags the channel selection as invalid.

Example `rust-toolchain.toml`:
```toml
[toolchain]
channel = "esp" # This is correct, the "esp" toolchain must be installed with "espup".
```

Error produced (some paths redacted):
```
[{
	"resource": "/home/*****/rust-toolchain.toml",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 8,
	"message": "\"esp\" does not match \"^(?:stable|beta|nightly|\\d+(?:\\.\\d+){1,2})(?:-\\d{4}(?:-\\d{2}){2})?(?:-\\D[^-]*(?:(?:-(?:[^-]+)){1,3}))?$\"",
	"source": "Even Better TOML",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 8
}]
```

Is there an option to disable this error, or to provide custom channel names?

**Comment by ia0** [comment]
I'm not sure how best to help you, but I can try to describe the problem and provide some links.

AFAICT, taplo is using schema store ([website](https://schemastore.org), [github](https://github.com/schemastore/schemastore/)), which defines [the following pattern](https://github.com/SchemaStore/schemastore/blob/bed8f29ddca68672d8d82e70a86614bf41a8ff99/src/schemas/json/rust-toolchain.json#L13) for `rust-toolchain.toml:toolchain.channel`, which is the issue you're hitting.

Since you're using VS Code, [this paragraph](https://github.com/tamasfe/taplo/tree/master/editors/vscode#completion-and-validation-with-json-schema) may be helpful to you. This leads to [this documentation](https://taplo.tamasfe.dev/configuration/using-schemas.html) which describes a few ways to change or disable the schema. Here's a 2 ways to disable the schema (I don't know how to write/patch a new one):
- Either disable schema completely in your `taplo.toml` with
```toml
[schema]
enabled = false
```
- Or disable based on some rule:
```toml
[[rule]]
include = ["rust-toolchain.toml"]

[rule.schema]
enabled = false
```

**Comment by hackguy25** [comment]
Thank you for your help! I managed to disable the schema by adding a directive to the file instead:
```toml
#:exclude .
# The above line disables "invalid toolchain" error generated by the Even Better TOML extension.

[toolchain]
channel = "esp" # This is correct, the "esp" toolchain must be installed with "espup".
```

I found that setting the `exclude` property can be achieved with a [directive](https://taplo.tamasfe.dev/configuration/directives.html), even though this is not directly documented.
