### ISSUE TITLE
Hatch support for “Even Better TOML”

### ISSUE THREAD

**Issue by flying-sheep** [tamasfe/taplo#432]
It would be great to have [Hatch](https://hatch.pypa.io/latest/) support in Even Better TOML, so we can efficiently write things like

```toml
[tool.hatch.envs.test]
dependencies = ["pytest-xdist"]
features = ["test"]
[tool.hatch.envs.test.scripts]
run = "pytest -v -n auto {args}"
cov = "run --cov-report=term-missing --cov=anndata {args}"
```
