### ISSUE TITLE
Formatter: Indent Tables, have some wrong at nest table

### ISSUE THREAD

**Issue by cool9203** [tamasfe/taplo#438]
Sorry for my english.

If title have wrong, help me to edit please, thanks.

Table have multi sub table, will not indent.
But only not work in some times.

Follow this two examples:

Before formatter
```toml
[table]
[table.t1]
[table.t1.c1]
[table.t2]
```

---

After formatter
```toml
[table]
    [table.t1]
        [table.t1.c1]
[table.t2]
```

---

Expected
```toml
[table]
    [table.t1]
        [table.t1.c1]
    [table.t2]
```

---

Another example for correct(Before formatter):
```toml
[table]
[table.t1]
[table.t2]
[table.t2.c1]
```

---

After formatter
```toml
[table]
    [table.t1]
    [table.t2]
        [table.t2.c1]
```

---

This is my setting with `Even Better TOML` in vscode:
```json
"evenBetterToml.formatter.alignComments": true,
"evenBetterToml.formatter.alignEntries": true,
"evenBetterToml.schema.catalogs": [],
"evenBetterToml.schema.enabled": false,
"evenBetterToml.taplo.configFile.enabled": false,
"evenBetterToml.formatter.indentEntries": false,
"evenBetterToml.formatter.indentTables": true,
"evenBetterToml.formatter.trailingNewline": true,
```

**Comment by sunerpy** [comment]
Maybe it need reviewed ? I only set the indent_tables = true.
Even Better TOML: v0.19.2
VS Code: 1.85.1

example codes:
```toml
[a]
    [a.b]
        [a.b.global]
        kube_redis_host = ""
    [a.c]
        [a.c.test]
            [a.c.test.global]
            password_cipher = false
[b]

```
But when I click to format this file, it changes:
```toml
[a]
    [a.b]
        [a.b.global]
        kube_redis_host = ""
[a.c]
    [a.c.test]
        [a.c.test.global]
        password_cipher = false
[b]
```
