### ISSUE TITLE
Even Better TOML doesn't respects "publish = false" for Cargo.toml

### ISSUE THREAD

**Issue by boozook** [tamasfe/taplo#440]
### Example toml
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
publish = false
```

### Problem

Even Better TOML throws errors for entire Cargo.toml like this
```
"Categories" is a required property
"License" is a required property
"Builds" is a required property
```

### Expected result

No errors because of property `publish` is set to `false` and some validations are unnecessary.

- - -

_Probably that is problem of schema, I don't know..._ 🤷🏻‍♂️

**Comment by ia0** [comment]
I am not able to reproduce. I create the following file named `Cargo.toml`:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
publish = false
```

And I don't get any errors neither with taplo-lsp, nor taplo-cli.
