### ISSUE TITLE
False positive error when using poetry's git dependency

### ISSUE THREAD

**Issue by evgenii-hb** [tamasfe/taplo#460]
Im trying to use github repo as a dependecy for my python project, the `pyproject.toml` looks like this
```toml
[tool.poetry]
name = "awesome_name"
version = "0.1.0"
description = "Cool project"

[tool.poetry.dependencies]
httplib = { git = "https://github.com/honestbank/data-science-feature-engineering-library.git", branch = "main" }
sshlib = { git = "git@github.com:honestbank/data-science-research-framework-library.git", branch = "main" }
```
Judjing by definitions here https://json.schemastore.org/pyproject.json , seems like there is a check whether field `git` is a valid url. Copy from the link:
```json
"poetry-git-dependency": {
      "type": "object",
      "required": ["git"],
      "additionalProperties": false,
      "properties": {
        "git": {
          "type": "string",
          "description": "The url of the git repository.",
          "format": "uri"
        },
        "branch": {
          "type": "string",
          "description": "The branch to checkout."
        },
```

So in my case `httplib` have correct url but `sshlib` do not. Hence taplo throws a false error.
