### ISSUE TITLE
Github Action / running taplo in CI

### ISSUE THREAD

**Issue by jbergstroem** [tamasfe/taplo#470]
It's easy enough to get taplo running in CI. Something like this should work (and version can be maintained with a regex in renovatebot):

```yaml
  taplo:
    name: Taplo
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Taplo
        env:
          version: "0.8.1"
        run: |
          curl -Ls "https://github.com/tamasfe/taplo/releases/download/${{ env.version }}/taplo-full-linux-x86_64.gz" | \
          gzip -d > taplo && \
          chmod +x taplo && \
          sudo mv taplo /usr/local/bin/taplo
      - name: Run Taplo
        run: taplo validate --colors never --no-schema
```

..that said. The very helpful CLI output is very complicated to parse with a [problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md).

One way to improve this could be to support a custom output template, [similar to actionlint](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#format-error-messages). Another approach could be to have a custom format specifically catering problem matchers (which also could serve as a way get improved editor support).
