### ISSUE TITLE
The wrong format from multi-line basic string

### ISSUE THREAD

**Issue by leolcao** [tamasfe/taplo#483]
From the https://toml.io/en/v1.0.0#string, I found the sample str7 will make the color style of rest part in toml file become to invalid style.

```toml
str4 = """Here are two quotation marks: "". Simple enough."""
# str5 = """Here are three quotation marks: """."""  # INVALID
str5 = """Here are three quotation marks: ""\"."""
str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""

# "This," she said, "is just a pointless statement."
str7 = """"This," she said, "is just a pointless statement.""""

# What you see is what you get.
winpath  = 'C:\Users\nodejs\templates'
winpath2 = '\\ServerX\admin$\system32\'
quoted   = 'Tom "Dubs" Preston-Werner'
regex    = '<\i\c*\s*>'


regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
```

result:

![image](https://github.com/tamasfe/taplo/assets/539695/9e41a23b-f9d7-41bc-89d9-0d9b49d9e249)

But, the syntax is right, and I still can use 'copy as json' to get right result.

```json
{
  "str4": "Here are two quotation marks: \"\". Simple enough.",
  "str5": "Here are three quotation marks: \"\"\".",
  "str6": "Here are fifteen quotation marks: \"\"\"\"\"\"\"\"\"\"\"\"\"\"\".",
  "str7": "\"This,\" she said, \"is just a pointless statement.\"",
  "winpath": "C:\\Users\\nodejs\\templates",
  "winpath2": "\\\\ServerX\\admin$\\system32\\",
  "quoted": "Tom \"Dubs\" Preston-Werner",
  "regex": "<\\i\\c*\\s*>",
  "regex2": "I [dw]on't need \\d{2} apples",
  "lines": "The first newline is\ntrimmed in raw strings.\n   All other whitespace\n   is preserved.\n"
}
```

vscode version: 1.82.2
extension version: v0.19.2
