### ISSUE TITLE
Syntax Highlighter gives wrong color coding when escaping double quotes ("") with equals (=) in between

### ISSUE THREAD

**Issue by deltamarnix** [tamasfe/taplo#516]
Make a TOML file with the following text:

```toml
[bar]
foo = { cmd = "julia --eval 'println(\"--check-bounds=yes\")'" }
zoo = { cmd = "julia --eval 'println(\"foo\")'"}
```

The extension wants to be smart with the `=` sign, but unfortunately it results in strange coloring. I have escaped the double quotes inside the double quotes.

![image](https://github.com/tamasfe/taplo/assets/150045289/7b7c6583-5a5b-478b-bf56-4d745417ff96)
