### ISSUE TITLE
Configuration files are not reloaded on save in vscode

### ISSUE THREAD

**Issue by bobrik** [tamasfe/taplo#528]
1. Have the following `derp.toml`:

```toml
rust-s3 = { version = "0.33", default-features = false, features = ["sync", "sync-rustls-tls"] }
```

2. Try to save it and observe that it expands the array:

```toml
rust-s3 = { version = "0.33", default-features = false, features = [
    "sync",
    "sync-rustls-tls",
] }
```

3. Add a config file `.taplo.toml` to prevent this:

```toml
include = ["*.toml"]

[formatting]
column_width = 120
array_auto_expand = false
```

4. Try saving `derp.toml` again and face the same expansion.
5. Reload vscode window and save it again to see the config applied.

Not picking up config file changes is counter-intuitive and very hard to understand. I went as far as compiling the extension myself to find it working after that.
