### ISSUE TITLE
Underscores in urls for pyproject.toml not supported for [tool.poetry.dependencies]

### ISSUE THREAD

**Issue by bavalpey** [tamasfe/taplo#572]
Sorry in advance if this isn't the right repository to file this issue under - I could not determine the source of the schema for this section of pyproject.toml.

I'm getting spurious validation errors for the urls in my [tool.poetry.dependencies] section.
It works for many of the entries, but any urls that have an underscore (or a few other characters like %20) in them are flagged as not matching the schema:
As an example pyproject.toml

```toml
[build-system]
requires = ["poetry-core"]

[tool.poetry]
name = "foo"
version = "0.1.0"
description = "my foo project"
authors = ["Name"]

[tool.poetry.dependencies]
my_repo = { git = "git@github.com:user/my_repo.git"}
```

This will report an error:
``{"git":"git@github.com:user-roc/my_repo.git"} is not valid under any of the given schemas``
