### ISSUE TITLE
Bug: align entries fails when one entry is multiline

### ISSUE THREAD

**Issue by hbaxter-sc** [tamasfe/taplo#595]
given a toml like this
```toml
[foo]
bar = 1
barbarbaz = { a = "b", c = "d" }
short = { short_key = "b", features = ["foo", "bar"] }
```

running
`taplo format t.toml --option align_entries=true` gives:
```toml
[foo]
bar       = 1
barbarbaz = { a = "b", c = "d" }
short     = { short_key = "b", features = ["foo", "bar"] }
```
 
however, if an entry is put over multiple lines, then:
```toml
[foo]
bar = 1
barbarbaz = { a = "b", c = "d" }
long = { long_key_name_here = "b", another_long_key_name_here = "d", features = ["foo","bar",] }
```

the same command with align_entries=true gives:
```toml
[foo]
bar = 1
barbarbaz = { a = "b", c = "d" }
long = { long_key_name_here = "b", another_long_key_name_here = "d", features = [
  "foo",
  "bar",
] }
```

which does not have the entries aligned, we would expect something like:
```toml
[foo]
bar       = 1
barbarbaz = { a = "b", c = "d" }
long      = { long_key_name_here = "b", another_long_key_name_here = "d", features = [
               "foo",
               "bar",
             ] }
```
