### ISSUE TITLE
Lint fails when date is before 1000AD

### ISSUE THREAD

**Issue by sorairolake** [tamasfe/taplo#613]
Lint fails (on `taplo-cli`) when date is before 1000AD as below:

```toml
date = 0781-04-30
datetime = 0645-06-12T12:00:00
```

Is this failure as expected? The valid years according to [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) are between 0000AD and 9999AD. So, I think these dates are valid.

```sh
$ taplo -V
taplo 0.9.1
```
