### ISSUE TITLE
Regression: `[rule.formatting]` completely overrides the default outside of the specified sections

### ISSUE THREAD

**Issue by rami3l** [tamasfe/taplo#634]
Hi there, and thanks for making this wonderful project!

The Rustup team is trying to use `taplo` across our project, however we have encountered the following regression after trying to upgrade `taplo` to v0.9.2 (from v0.9.0):

With the following `.taplo.toml` on `taplo` v0.9.2:

```toml
include = ["**/*.toml"]

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "workspace.dependencies",
]

[rule.formatting]
reorder_keys = true
```

... and the following (minimal reproduction) `Cargo.toml`:

```toml
[package]
name = "rustup"
version = "1.27.1"
edition = "2021"
description = "Manage multiple rust installations with ease"
homepage = "https://github.com/rust-lang/rustup"
keywords = ["rustup", "multirust", "install", "proxy"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rustup"
build = "build.rs"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
anyhow.workspace = true
cfg-if = "1.0"
clap = { version = "4", features = ["derive", "wrap_help"] }
```

... you can see that after `taplo fmt`, the keys in the `[dependencies]` section are sorted alphabetically (as expected). However, the keys in the `[package]` section are also reordered (which is not the case for v0.9.0):

```toml
[package]
build = "build.rs"
description = "Manage multiple rust installations with ease"
edition = "2021"
homepage = "https://github.com/rust-lang/rustup"
keywords = ["rustup", "multirust", "install", "proxy"]
license = "MIT OR Apache-2.0"
name = "rustup"
readme = "README.md"
repository = "https://github.com/rust-lang/rustup"
version = "1.27.1"

[dependencies]
anyhow.workspace = true
cfg-if = "1.0"
chrono = { version = "0.4", default-features = false, features = ["std"] }
clap = { version = "4", features = ["derive", "wrap_help"] }
```

Many thanks in advance!
