### ISSUE TITLE
request: organize by type

### ISSUE THREAD

**Issue by nrdxp** [tamasfe/taplo#661]
It'd be a nice option to enforce whitespace separation between individual types in a large table, as you can already do with manual spacing (and thank you :pray:)
## by type:
```toml
[table]
hello = 1
bye   = 2

some  = "string"
other = "str"

well = { again = "hello" }
now  = { yes = "no" }

nothing   = [ ]
something = [ 1 ]
```

Here scalar types take precendent. Each type is split into groups by type with composites coming last.

-----

You could be less granular and simply distinguish between scalar and composite types.
## by order:
```toml
[table]
hello = 1
some  = "string"

well    = { again = "hello" }
nothing = []
```

This would still go a long way to make some space.
