### ISSUE TITLE
reorder_keys does not sort if there are comments

### ISSUE THREAD

**Issue by tv42** [tamasfe/taplo#675]
```console
$  taplo --version
taplo 0.9.3

$ cat bug.toml
[pleasesort]
z = 2
# test
a = 1

$ cat bug.toml | taplo format --no-auto-config -o reorder_keys=true bug.toml -
[pleasesort]
z = 2
# test
a = 1

$ grep -v '^#' bug.toml | taplo format --no-auto-config -o reorder_keys=true -
[pleasesort]
a = 1
z = 2
```

**Comment by tv42** [comment]
It seems a blank line will also prevent reorder_keys.

**Comment by panekj** [comment]
This is correct behaviour, a comment might refer to specific line so it shouldn't be moved anywhere else

**Comment by tv42** [comment]
You could choose to do what a lot of code refactoring does: assume a full-line comment describes an immediately-following non-comment line.

**Comment by panekj** [comment]
But that is a wrong assumption because that comment doesn't have to refer to next line

**Comment by tv42** [comment]
Even in the world you are advocating for where comments cannot be tied to uncommented lines, commenting out a line silently breaking reordering sounds unpleasant :-(

**Comment by tv42** [comment]
Here's another reason full line comments seem superior to me:

```toml
[[rule]]
include = ["deny.toml"]
# WAITING https://github.com/tamasfe/taplo/issues/608
#keys = ["graph.targets", "licenses.allow", "licenses.exceptions.allow"]
keys = ["graph", "licenses"]
formatting = { reorder_arrays = true }
```
