### ISSUE TITLE
All children inherit parent invalidations

### ISSUE THREAD

**Issue by RivenSkaye** [tamasfe/taplo#699]
Having a schema that disallows additional properties in every level of nesting and then adding an additional property in the parent element makes Taplo (both the VSC extension and the CLI lint) repeat the error for that single disallowed value on every level of children and all of their properties.

MRE:
schema
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "additionalProperties": false,
    "title": "config.toml",
    "description": "A schema to validate against my own stupidity.",
    "type": "object",
    "properties": {
        "db": {
            "additionalProperties": false,
            "description": "Database Configuration",
            "type": "object",
            "properties": {
                "mysql": {
                    "additionalProperties": false,
                    "type": "object",
                    "properties": {
                        "pool": {"type": "boolean"},
                        "other": {
                            "additionalProperties": false,
                            "type": "object",
                            "properties" : {
                                "database": {"type": "string"}
                            }
                        }
                    }
                },
                "postgres": {
                    "additionalProperties": false,
                    "type": "object",
                    "properties": {
                        "pool": {"type": "boolean"},
                        "other": {
                            "additionalProperties": false,
                            "type": "object",
                            "properties" : {
                                "database": {"type": "string"}
                            }
                        }
                    }
                },
                "sqlite": {
                    "additionalProperties": false,
                    "type": "object",
                    "properties": {
                        "wal_mode": {"type": "boolean"},
                        "other": {
                            "additionalProperties": false,
                            "type": "object",
                            "properties" : {
                                "db_file_path": {"type": "string"}
                            }
                        }
                    }
                }
            }
        }
    }
}
```
toml
```toml
[db]
hodor = true  # invalid property, should only generate one warning, 2 if value validation still happens

# Every single key and value below this is being reported on,
# with the error that 'hodor' was unexpected!
[db.mysql]
pool = true
# moving hodor here makes only the db.mysql tree error out the wazoo
[db.mysql.other]
database = "mysuperawesomedb"

[db.postgres]
pool = true
[db.postgres.other]
database = "mysuperawesomedb"

[db.sqlite]
wal_mode = true
[db.sqlite.other]
db_file_path = "/my/super/awesome.db"
```
