### ISSUE TITLE
.taplo.toml not works when using `taplo fmt -` (from stdin)

### ISSUE THREAD

**Issue by lxl66566** [tamasfe/taplo#704]
I wrote a `.taplo.toml` in the current folder:

```toml
include = ["**/*.toml"]

[[rule]]
include = ["**/Cargo.toml", ".taplo.toml", "Cargo.toml", "rustfmt.toml"]

[rule.formatting]
align_comments       = true
align_entries        = true
array_trailing_comma = true
column_width         = 100
inline_table_expand  = false
reorder_keys         = true
trailing_newline     = true
```

when i run `taplo fmt Cargo.toml`, it can be formatted correctly. 

```toml
[package]
edition = "2021"
name    = "test_rs"
version = "0.1.0"

[dependencies]
```

But if I run `taplo fmt - < Cargo.toml`, it outputs:

```
$ taplo fmt - < Cargo.toml
 INFO taplo:format_stdin:load_config: found configuration file path="D:/program/Rust/test_rs/.taplo.toml"
[package]
edition = "2021"
name = "test_rs"
version = "0.1.0"

[dependencies]
```

This content is formatted, but `.taplo.toml` config not work.

I guess the stdin is not in the *include* of `.taplo.toml`, so the configuration will not be applied to it?

addtional info:
- using the latest version v0.9.3

update: I found that I should use `--stdin-filepath "Cargo.toml"` to match the include rule in the config. But I don't think *do not match config file by default* is a good behavior?
