### ISSUE TITLE
Cargo.toml doesn't support resolver = "3"

### ISSUE THREAD

**Issue by tgrushka** [tamasfe/taplo#714]
```toml
[workspace]
resolver = "3"
```

is not supported. It gives error:
```"3" is not one of ["1","2"]```

There are no clear instructions on how to override this in `evenBetterToml` settings.
