### ISSUE TITLE
Formatter splits nested array across multiple lines unnecessarily

### ISSUE THREAD

**Issue by UtkarshVerma** [tamasfe/taplo#724]
I have the following toml.

```toml
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	# Disable defaults
	{ on = [ "g", "h" ], run = "noop" },
]
```

taplo keeps formatting this as the following:

```toml
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	# Disable defaults
	{ on = [
		"g",
		"h",
	], run = "noop" },
]
```

I really like how concise the previous layout is. Is there any way to tell it not do anything here?
