### ISSUE TITLE
Commenting indentation follows section above, not section below

### ISSUE THREAD

**Issue by kevincantu** [tamasfe/taplo#77]
Say I want to have two sections and some tables in each, and descriptive comments on their own lines above each section:
```toml
#############################################################################
# envoy logs
#############################################################################

[xyz]
Sampler = "RulesBasedSampler"

# Since the only(?) contents of this dataset are Envoy logs,
# this dataset's rules don't matter until refinery learns how
# to sample events without a trace id!

  [[xyz.rule]]
  name = "is default"
  SampleRate = 1


#############################################################################
# my apps
#############################################################################

[abc]
Sampler = "RulesBasedSampler"

  ########################################################################
  # health-checks
  ########################################################################

  [[abc.rule]]
  name = "is a health-check" 
  SampleRate = 100 # keep 1/100
    [[abc.rule.condition]]
    field = "request.path"
    operator = "=="
    value = "/health-check"
```

Actually Even Better TOML's table indentation system goes and puts those comments at indentation levels trailing previous expressions:
```
```toml

#############################################################################
# envoy logs
#############################################################################

[xyz]
Sampler = "RulesBasedSampler"

# Since the only(?) contents of this dataset are Envoy logs,
# this dataset's rules don't matter until refinery learns how
# to sample events without a trace id!

  [[xyz.rule]]
  name = "is default"
  SampleRate = 1


  #############################################################################
  # OOPS >>
  #############################################################################

[abc]
Sampler = "RulesBasedSampler"

########################################################################
# OOPS <<
########################################################################

  [[abc.rule]]
  name = "is a health-check" 
  SampleRate = 100 # keep 1/100
    [[abc.rule.condition]]
    field = "request.path"
    operator = "=="
    value = "/health-check"
```

Can you make them float better?

**Comment by tamasfe** [comment]
Right now every comment is treated just like an entry everywhere for the sake of simplicity, but I agree it is sub-optimal.

Usually comments are descriptions about the item beneath them, and what you're suggesting aligns with this statement, but it's not always the case. Consider the following:

```toml
[settings]

opt1 = true
opt2 = false

# Add more options here. <- Does this belong under "settings" or is it part of "settings.gui"?

  # UI settings. <- Belongs to "settings.gui"
  [settings.gui]
```

I'm also in favor of implementing what you suggest, but we need to deal with cases like this first in a predictable and straightforward manner.

Currently I have the following options in my mind:
- **1**: The last comment group is always part of the next item, even if separated by empty lines.
- **2**: If there is no empty line between a comment group and an item below, it is always considered to be part of that item.

Example formatting for **1**:
```toml
[settings]

# settings comments
# more settings comments

  # settings.gui comments
  # more settings.gui comments

  [settings.gui]
```
However:
```toml
[settings]

  # settings comments
  # more settings comments
  # Omitting settings.gui comments causes indentation of this.

  [settings.gui]
```

Example formatting for **2**:
```toml
[settings]

# settings comments
# more settings comments

# settings.gui comments
# more settings.gui comments
# not indented as there is an empty line between this and the item

  [settings.gui]
```
```toml
[settings]

# settings comments
# more settings comments

# more comments

  # settings.gui comments
  # more settings.gui comments
  [settings.gui]
```

I personally prefer **2**, but I need more input on this.
