### ISSUE TITLE
`taplo.toml` applies global schema to itself

### ISSUE THREAD

**Issue by ninjack-dev** [tamasfe/taplo#782]
Currently, when using Taplo as a language server, setting the `[schema]` in a Taplo config file applies the schema to the Taplo config file itself, whereas normally it would apply the proper schema (this example uses the [schema for an Oh My Posh prompt configuration file](https://ohmyposh.dev/docs/configuration/general#json-schema-validation)):

![Image](https://github.com/user-attachments/assets/0ede50c6-22ad-42a2-b837-6cc294cb682c)

A workaround is to create a rule which excludes the config file:
```toml
[[rule]]
  exclude = [ ".taplo.toml" ]

[rule.schema]
  path = "path/to/schema.json"
```

A default rule to exclude `taplo.toml`/`.taplo.toml` from any global schema would be a nice feature.
