### ISSUE TITLE
Wrong formatting when the next table is preceded by whitespace-only lines

### ISSUE THREAD

**Issue by toasteater** [tamasfe/taplo#91]
Using version 0.10.0 of the VS Code extension, when formatting the following document:

```toml
# here, the line directly above [bar] contains one single space, but the problem is
# triggered by any number of lines containing any number of spaces.
[foo]
foo = "bar"
bar = "foo"
 
[bar]
foo = "bar"
```

Expected result:

```toml
# the space is removed. there is an empty line directly above [bar]
[foo]
foo = "bar"
bar = "foo"

[bar]
foo = "bar"
```

Actual result:

```toml
# the empty line is placed under [foo] instead
[foo]

foo = "bar"
bar = "foo"
[bar]
foo = "bar"
```
