### ISSUE TITLE
Inline table minification

### ISSUE THREAD

**Issue by Cryptkeeper** [tamasfe/taplo#92]
Perhaps against the spirit of TOML, some of configs use inline tables. The issue I'm encountering is when being re-formatted by taplo the inline tables are expanded into nested tables. Let's be honest, this is not an issue. It is mostly a QOL ask.

```toml
[person]
name = "Bob"
birthday = {month = 1, day = 1, year = 1970}
```

When reformatted using taplo, the inline table is expanded (rough example):

```toml
[person]
name = "Bob"

[person.birthday]
day = 1
month = 1
year = 1970
```

Is there anyway to re-format the expanded table back into an inline table? Besides determining when to re-format as an inline table (perhaps using the line length?), it is possibly complicated by inline array tables. For example, merging nested array tables back into a singular inline array table:

```toml
[person]

[[person.friends]]
name = "Joe"

[[person.friends]]
name = "Fred"
```

```toml
[person]
friends = [{name = "Joe"}, {name = "Fred"}]
```
