### ISSUE TITLE
Comment directives

### ISSUE THREAD

**Issue by tamasfe** [tamasfe/taplo#97]
I was originally against all kinds of metadata in comments, however they definitely make life easier sometimes.

The tools should probably support some kind of _comment directives_. What the syntax should look like is not yet decided.

The LSP currently considers comments that start with `#:` directives, and supports a `schema` directive as well.
TOML documents thus can tell what schema they should be used with, for example:

```toml
#:schema https://example.com/schema.json
[table]
value = "value"
# ...
```

I'm not sure if this is the right approach though.
